---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-sync-config
  namespace: ldap-group-sync
data:
  ldap-group-sync.yaml: |
    kind: "LDAPSyncConfig"
    apiVersion: "v1"
    url: ldap://192.168.1.10:389/DC=konsalt,DC=info?sAMAccountName?sub
    bindDN: CN=svcintuser,OU=Konsalt,DC=konsalt,DC=info
    bindPassword:
      file: "/ldap-sync/secrets/bindPassword"
    insecure: true
    rfc2307:
      groupsQuery:
        baseDN: DC=konsalt,DC=info
        derefAliases: never
        filter: '(|(cn=REDHAT*))'
      groupUIDAttribute: dn
      groupNameAttributes:
      - cn
      groupMembershipAttributes:
      - member
      usersQuery:
        baseDN: DC=konsalt,DC=info
        derefAliases: never
      userUIDAttribute: dn
      userNameAttributes:
      - sAMAccountName
