apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap-ldap-sync-config.yaml
- configmap-opentlc-ipa-tls-ca.yaml
- cronjob.yaml
- namespace.yaml
- serviceaccount.yaml
